import { BoardArt } from './BoardArt';
import { Icon } from './Icon';
import { StatCard } from './StatCard';
import { useGameStore } from '../store/store';
import { properties, netWorth } from '../game/portfolio';
import { formatXlm } from '../lib/format';
export function Home({ onPlay }: { onPlay: () => void }) {
  const match = useGameStore(state => state.match);
  const setPage = useGameStore(state => state.setPage);
  const resume = match && match.phase !== 'finished';
  return <div className="home-page"><div className="page-intro"><div><p className="eyebrow">A NEW WAY TO PLAY THE NETWORK</p><h1>Big ideas. Bigger moves<span className="lime-text">.</span></h1><p>Your seat at the table is ready. Let’s build something of your own.</p></div><span className="edition-label"><Icon name="spark" size={16} /> THE STELLAR EDITION</span></div>
    <section className="hero-card" aria-labelledby="hero-title"><div className="hero-copy"><span className="hero-tag"><span className="status-dot" /> A classic game. A new frontier.</span><h2 id="hero-title">Own the board.<br />Learn the network.</h2><p>Build your portfolio, outsmart your opponent, and discover the world of Stellar. Your first move is on us.</p><div className="hero-actions"><button className="button lime" onClick={() => resume ? setPage('game') : onPlay()}>{resume ? 'Continue your game' : 'Let’s play'}<Icon name="arrow" size={18} /></button><button className="hero-learn" onClick={() => setPage('learn')}>How it works <Icon name="chevron" size={16} /></button></div><span className="hero-footnote"><Icon name="check" size={14} /> No wallet needed <span>·</span> Free to explore <span>·</span> Play at your pace</span></div><BoardArt /></section>
    <div className="stats-grid"><StatCard icon="wallet" label={match ? 'Your balance' : 'Starting balance'} value={formatXlm(match?.players.you.balance ?? 1500)} detail="Practice funds. Real possibilities." /><StatCard icon="board" label="Properties owned" value={String(match ? properties(match, 'you').length : 0).padStart(2, '0')} detail="A whole network to make your own." /><StatCard icon="trophy" label={match ? 'Your net worth' : 'Your next challenge'} value={match ? formatXlm(netWorth(match, 'you')) : 'You vs. Orbit'} detail={match ? 'Your cash + property purchase value.' : 'An AI opponent. Three difficulty levels.'} /></div>
    <div className="home-lower"><section className="quick-play"><div className="section-heading"><h2>Find your next game</h2><span className="subtle-label">ONE GOOD MOVE STARTS IT ALL</span></div><div className="game-card"><div className="game-cover"><span className="cover-orbit" /><span className="cover-dice">⚄</span><span className="cover-star">✧</span><span className="cover-label">THE ORIGINAL</span></div><div className="game-description"><span className="mini-badge">SOLO PRACTICE</span><h3>Small board. Big ambition.</h3><p>The classic property game, reimagined for the Stellar ecosystem.</p><div className="game-meta"><span><Icon name="board" size={14} />40 spaces</span><span><Icon name="refresh" size={14} />30 rounds</span><span><Icon name="spark" size={14} />3 levels</span></div></div><button className="round-button" onClick={onPlay} aria-label="Set up a new practice game"><Icon name="arrow" /></button></div></section><section className="learn-card"><span className="learn-icon"><Icon name="book" size={23} /></span><span className="eyebrow">CURIOUS? GOOD.</span><h2>Learn by making<br />your next move.</h2><p>Properties, portfolios, and a little strategy. We’ll show you the ropes.</p><button className="text-button" onClick={() => setPage('learn')}>Get to know the game<Icon name="arrow" size={17} /></button></section></div>
    <footer className="page-footer"><span>Made for curious minds. Built around Stellar.</span><span>Play. Learn. Own your next move. <span aria-hidden="true">✳</span></span></footer>
  </div>;
}
